# https://symfony.com/doc/current/translation.html

# config/packages/translation.yaml
parameters:
  translator.logging: true

framework:
  default_locale: en
  enabled_locales: [ en, ru, ua ]
  translator:
    default_path: '%kernel.project_dir%/translations'
    providers:
      loco:
        dsn: '%env(LOCO_DSN)%'
        domains: [ messages ]
        locales: [ en, ru, ua ]