# https://symfony.com/doc/current/configuration.html
# https://symfony.com/doc/current/service_container.html

# config/services.yaml
# https://symfony.com/doc/current/configuration.html#configuration-parameters
parameters:
  # framework.notifications.email_sender: 'anonymous@example.com'

# https://symfony.com/doc/current/service_container.html#creating-configuring-services-in-the-container
services:
  # default configuration for services in *this* file
  _defaults:
    autowire: true      # Automatically injects dependencies in your services.
    autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
    # https://symfony.com/doc/current/configuration.html#accessing-configuration-parameters
    bind:
      # this allows to define the scalar arguments once and apply them to any services
      # defined/created in this file; if some argument is used rarely, instead of defining
      # it here you can use the #[Autowire] attribute to inject it manually in the service constructor

  # makes classes in src/ available to be used as services
  # this creates a service per class whose id is the fully-qualified class name
  Application\:
    resource: '../src/Application'
  Framework\:
    resource: '../src/Framework'
  # order is important in this file because service definitions
  # always *replace* previous ones; add your own service configuration below

# https://symfony.com/doc/current/service_container/factories.html
  Prooph\EventStore\EventStoreConnection:
    factory: [ Prooph\EventStoreClient\EventStoreConnectionFactory, 'createFromUri' ]
    arguments:
     # $connectionString: 'esdb://localhost:2111?tls=true&tlsVerifyCert=false'